name: Build master

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Master buld tests
        run: |
          make test   
    
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Run build & push
        run: |
          make docker/build
          make docker/push

